name: CD - Deploy to AWS (Lambda + API Gateway)

on:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  S3_BUCKET: acme-registry-deployments-052747538576-us-east-1
  STACK_NAME: acme-registry-staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    # environment: staging
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::052747538576:role/GitHubOIDCDeployRole
          aws-region: ${{ env.AWS_REGION }}

      - name: Install AWS SAM CLI and AWS CLI
        run: |
          pip install awscli aws-sam-cli

      - name: Build (SAM)
        run: sam build --use-container

      - name: Deploy (SAM)
        run: |
          sam deploy \
            --stack-name ${{ env.STACK_NAME }} \
            --s3-bucket ${{ env.S3_BUCKET }} \
            --capabilities CAPABILITY_IAM \
            --no-fail-on-empty-changeset \
            --region ${{ env.AWS_REGION }}

      - name: Tail Lambda logs on failure
        if: failure()
        run: |
          echo "Skipping log tail due to AWS CLI v2 incompatibility."

